# Generated by Django 4.0.3 on 2022-03-22 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_verificate', 'Может верифицировать'),)},
        ),
    ]
