# Generated by Django 4.0.3 on 2022-03-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_and_comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
