# Generated by Django 4.0.3 on 2022-03-22 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_and_comments', '0002_alter_news_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'permissions': (('can_publicate', 'Может опубликовать'),), 'verbose_name_plural': 'News'},
        ),
    ]
