# Generated by Django 4.0.3 on 2022-03-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_and_comments', '0004_tags_news_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='tags',
        ),
        migrations.AddField(
            model_name='tags',
            name='news',
            field=models.ManyToManyField(to='news_and_comments.news'),
        ),
    ]
